openapi: 3.2.0
info:
  title: Testflinger API
  version: 1.0.0
servers:
- url: https://testflinger.ps7.canonical.com/
tags:
- name: Testflinger API
paths:
  /v1/:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful response
      tags:
      - Testflinger API
      summary: Identify ourselves
      operationId: getV1
      x-operation-id-source: derived
